#!/usr/bin/env python3
# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""
Embed binary files (like .hsaco) as C++ source code.

Usage:
    python embed_binary.py <input.hsaco> <output_basename> [--namespace=<ns>]

This will generate:
    - <output_basename>.hpp - Header with declaration
    - <output_basename>.cpp - Source with the embedded data

The binary is split into chunks of MAX_CHUNK_SIZE bytes to avoid
compiler issues with very large array constants.

Example:
    python embed_binary.py vector_add.hsaco kernels/vector_add --namespace=hip_cts::kernels
"""

import argparse
import os
import sys
from pathlib import Path

# Maximum bytes per array constant (to avoid compiler issues)
MAX_CHUNK_SIZE = 4096


def to_c_identifier(name: str) -> str:
    """Convert a filename to a valid C identifier."""
    # Replace non-alphanumeric chars with underscores
    result = ""
    for c in name:
        if c.isalnum():
            result += c
        else:
            result += "_"
    # Ensure it doesn't start with a digit
    if result and result[0].isdigit():
        result = "_" + result
    return result


def format_bytes_as_array(data: bytes, bytes_per_line: int = 16) -> str:
    """Format binary data as a C array initializer."""
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_values},")
    return "\n".join(lines)


def generate_header(
    identifier: str,
    namespace: str | None,
) -> str:
    """Generate the header file content."""
    
    ns_open = ""
    ns_close = ""
    if namespace:
        parts = namespace.split("::")
        ns_open = "\n".join(f"namespace {p} {{" for p in parts)
        ns_close = "\n".join(f"}} // namespace {p}" for p in reversed(parts))
    
    return f"""// Auto-generated file - do not edit
// Generated by embed_binary.py

#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>

{ns_open}

// Embedded binary data for {identifier}
struct {identifier}_data {{
    // Returns the embedded binary data as a vector
    static std::vector<uint8_t> get();
    
    // Returns the size of the embedded data in bytes
    static size_t size();
}};

{ns_close}
"""


def generate_source(
    identifier: str,
    namespace: str | None,
    header_name: str,
    data: bytes,
    chunk_size: int = MAX_CHUNK_SIZE
) -> str:
    """Generate the source file content with chunked arrays."""
    
    ns_open = ""
    ns_close = ""
    if namespace:
        parts = namespace.split("::")
        ns_open = "\n".join(f"namespace {p} {{" for p in parts)
        ns_close = "\n".join(f"}} // namespace {p}" for p in reversed(parts))
    
    # Split data into chunks
    chunks = []
    for i in range(0, len(data), chunk_size):
        chunk_data = data[i:i + chunk_size]
        chunks.append(chunk_data)
    
    # Generate array declarations for each chunk
    chunk_arrays = []
    for i, chunk in enumerate(chunks):
        array_content = format_bytes_as_array(chunk)
        chunk_arrays.append(f"""const uint8_t k_{identifier}_chunk_{i}[] = {{
{array_content}
}};""")
    
    chunks_code = "\n\n".join(chunk_arrays)
    
    # Generate the concatenation code
    total_size = len(data)
    
    # Build the reserve and insert calls
    insert_calls = []
    for i in range(len(chunks)):
        insert_calls.append(
            f"    result.insert(result.end(), "
            f"std::begin(k_{identifier}_chunk_{i}), "
            f"std::end(k_{identifier}_chunk_{i}));"
        )
    insert_code = "\n".join(insert_calls)
    
    return f"""// Auto-generated file - do not edit
// Generated by embed_binary.py

#include "{header_name}"
#include <iterator>

{ns_open}

namespace {{

{chunks_code}

}} // anonymous namespace

std::vector<uint8_t> {identifier}_data::get() {{
    std::vector<uint8_t> result;
    result.reserve({total_size});
{insert_code}
    return result;
}}

size_t {identifier}_data::size() {{
    return {total_size};
}}

{ns_close}
"""


def main():
    parser = argparse.ArgumentParser(
        description="Embed binary files as C++ source code"
    )
    parser.add_argument(
        "input",
        help="Input binary file (e.g., .hsaco)"
    )
    parser.add_argument(
        "output",
        help="Output basename (without extension)"
    )
    parser.add_argument(
        "--namespace",
        default=None,
        help="C++ namespace (e.g., 'hip_cts::kernels')"
    )
    parser.add_argument(
        "--identifier",
        default=None,
        help="C++ identifier name (defaults to input filename)"
    )
    parser.add_argument(
        "--max-chunk-size",
        type=int,
        default=MAX_CHUNK_SIZE,
        help=f"Maximum bytes per array constant (default: {MAX_CHUNK_SIZE})"
    )
    
    args = parser.parse_args()
    
    # Use chunk size from args (don't modify global)
    chunk_size = args.max_chunk_size
    
    # Read input file
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file '{args.input}' not found", file=sys.stderr)
        return 1
    
    with open(input_path, "rb") as f:
        data = f.read()
    
    if len(data) == 0:
        print(f"Error: Input file '{args.input}' is empty", file=sys.stderr)
        return 1
    
    # Determine identifier
    if args.identifier:
        identifier = to_c_identifier(args.identifier)
    else:
        identifier = to_c_identifier(input_path.stem)
    
    # Generate output paths
    output_base = Path(args.output)
    header_path = output_base.with_suffix(".hpp")
    source_path = output_base.with_suffix(".cpp")
    
    # Create output directory if needed
    output_base.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate files
    header_content = generate_header(identifier, args.namespace)
    source_content = generate_source(
        identifier, 
        args.namespace, 
        header_path.name,
        data,
        chunk_size
    )
    
    # Write files
    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"Generated: {header_path}")
    
    with open(source_path, "w") as f:
        f.write(source_content)
    print(f"Generated: {source_path}")
    
    num_chunks = (len(data) + chunk_size - 1) // chunk_size
    print(f"Embedded {len(data)} bytes as '{identifier}' ({num_chunks} chunks)")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
